import urllib.request
import json
import time

movies_raw = [
    ("Dune: Part Two", "Denis Villeneuve", 2024, 4.8, 4.6, ["Sci-Fi", "Epic", "Visual Masterpiece"], "A sweeping continuation that doubles down on scale, politics, and jaw-dropping desert cinematography.", "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.", "2h 46m", "HBO Max / Theaters", ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"], "Way9Dexny3w", ["hbo", "prime", "appleTv"]),
    ("Oppenheimer", "Christopher Nolan", 2023, 4.7, 4.5, ["Biopic", "Historical", "Oscar Winner"], "A tense, psychological portrait of the man who shaped the modern world in fire and shadow.", "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", "3h", "Peacock / Amazon Prime", ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr."], "bK6ldnjE3Y0", ["peacock", "prime"]),
    ("Inside Out 2", "Pixar", 2024, 4.4, 4.6, ["Animation", "Family", "Emotional"], "A warm, witty return that delicately maps the messy emotions of growing up.", "Riley enters her teenage years, and new emotions like Anxiety, Envy, and Embarrassment arrive at Headquarters.", "1h 36m", "Disney+", ["Amy Poehler", "Maya Hawke", "Kensington Tallman"], "LEjhY15eCx0", ["disney"]),
    ("Poor Things", "Yorgos Lanthimos", 2023, 4.5, 4.2, ["Surreal", "Comedy", "Drama"], "A bizarre, beautiful, and boldly original fairy tale for adults.", "The incredible tale and fantastical evolution of Bella Baxter, a young woman brought back to life by Dr. Godwin Baxter.", "2h 21m", "Hulu / Disney+", ["Emma Stone", "Mark Ruffalo", "Willem Dafoe"], "RlbR5N6veqw", ["hulu", "disney"]),
    ("Spider-Man: Across the Spider-Verse", "Joaquim Dos Santos", 2023, 4.9, 4.8, ["Animation", "Superhero", "Action"], "Visual audacity meets emotional resonance in a groundbreaking superhero masterpiece.", "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.", "2h 20m", "Netflix", ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"], "cqGjhVJWtEg", ["netflix", "appleTv"]),
    ("The Dark Knight", "Christopher Nolan", 2008, 4.9, 4.9, ["Action", "Crime", "Classic"], "The definitive modern comic book movie that transcends the genre.", "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.", "2h 32m", "HBO Max", ["Christian Bale", "Heath Ledger", "Aaron Eckhart"], "EXeTwQWrcwY", ["hbo", "prime"]),
    ("Interstellar", "Christopher Nolan", 2014, 4.8, 4.8, ["Sci-Fi", "Space", "Mind-Bending"], "A breathtaking space epic about time, gravity, and fatherly love.", "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "2h 49m", "Paramount+", ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"], "zSWdZVtXT7E", ["paramount", "prime"]),
    ("Inception", "Christopher Nolan", 2010, 4.8, 4.7, ["Sci-Fi", "Action", "Thriller"], "A mind-bending heist inside the subconscious that redefined action filmmaking.", "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", "2h 28m", "HBO Max", ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"], "YoHD9XEInc0", ["hbo", "appleTv"]),
    ("Parasite", "Bong Joon Ho", 2019, 4.9, 4.7, ["Thriller", "Satire", "Oscar Winner"], "A razor-sharp social satire that builds to an unforgettable crescendo.", "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", "2h 12m", "Hulu", ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"], "5xH0HfJHsaY", ["hulu", "prime"]),
    ("Everything Everywhere All at Once", "Daniel Kwan", 2022, 4.8, 4.6, ["Sci-Fi", "Multiverse", "Comedy"], "An inventive multiverse explosion packed with heart, philosophy, and martial arts.", "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.", "2h 19m", "Paramount+", ["Michelle Yeoh", "Ke Huy Quan", "Jamie Lee Curtis"], "wxN1T1uxQ2g", ["paramount", "prime"]),
    ("Barbie", "Greta Gerwig", 2023, 4.4, 4.3, ["Comedy", "Satire", "Pop Culture"], "A colorful, whip-smart satire about identity and womanhood in a plastic world.", "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.", "1h 54m", "HBO Max", ["Margot Robbie", "Ryan Gosling", "America Ferrera"], "pBk4NYhWNMM", ["hbo", "prime"]),
    ("Anatomy of a Fall", "Justine Triet", 2023, 4.6, 4.3, ["Drama", "Mystery", "Courtroom"], "An icy, deeply gripping courtroom drama dissecting a marriage under trial.", "A woman is suspected of murder after her husband's death, and their blind son faces a moral dilemma as the sole witness.", "2h 31m", "Hulu", ["Sandra Hüller", "Swann Arlaud", "Milo Machado-Graner"], "fTrsp5q6uLg", ["hulu", "prime"]),
    ("The Zone of Interest", "Jonathan Glazer", 2023, 4.7, 4.1, ["Drama", "Historical", "Chilling"], "A chilling masterpiece examining the banality of evil right next door.", "Auschwitz commandant Rudolf Höss and his wife Hedwig strive to build a dream life for their family in a house and garden next to the camp.", "1h 45m", "HBO Max", ["Christian Friedel", "Sandra Hüller", "Johann Karthaus"], "r-vfg3KkV54", ["hbo", "prime"]),
    ("Civil War", "Alex Garland", 2024, 4.2, 4.1, ["Action", "Thriller", "Dystopian"], "A visceral, sobering journey through a photojournalist lens in a fractured America.", "A team of military-attached journalists travels across the United States during the rapidly escalating Second American Civil War.", "1h 49m", "Amazon Prime / VOD", ["Kirsten Dunst", "Wagner Moura", "Cailee Spaeny"], "aDyQxtg0V2w", ["prime", "appleTv"]),
    ("Challengers", "Luca Guadagnino", 2024, 4.5, 4.4, ["Drama", "Romance", "Sports"], "A high-voltage romantic triangle set on and off the tennis court.", "Tashi, a tennis player turned coach, has transformed her husband into a champion. But to overcome a losing streak, he must face his former best friend.", "2h 11m", "MGM+ / Amazon Prime", ["Zendaya", "Josh O'Connor", "Mike Faist"], "VobTTg-83og", ["prime", "appleTv"]),
    ("Furiosa: A Mad Max Saga", "George Miller", 2024, 4.6, 4.4, ["Action", "Sci-Fi", "Post-Apocalyptic"], "An epic, rust-and-gasoline revenge odyssey across the Wasteland.", "The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max in Fury Road.", "2h 28m", "HBO Max / VOD", ["Anya Taylor-Joy", "Chris Hemsworth", "Tom Burke"], "XJMuhwVlca4", ["hbo", "prime"]),
    ("Kingdom of the Planet of the Apes", "Wes Ball", 2024, 4.3, 4.2, ["Sci-Fi", "Action", "Adventure"], "A worthy, visually stunning chapter setting up a new era for ape civilization.", "Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question everything he's been taught about the past.", "2h 25m", "Hulu", ["Owen Teague", "Freya Allan", "Kevin Durand"], "XtFI7SNtVpY", ["hulu", "disney"]),
    ("Godzilla Minus One", "Takashi Yamazaki", 2023, 4.8, 4.9, ["Action", "Monster", "Historical"], "A harrowing, emotional monster movie with astonishing depth and spectacle.", "Post-war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.", "2h 5m", "Netflix", ["Ryunosuke Kamiki", "Minami Hamabe", "Yuki Yamada"], "VvSrHIX5a-0", ["netflix"]),
    ("Past Lives", "Celine Song", 2023, 4.7, 4.6, ["Romance", "Drama", "Intimate"], "A delicate, soul-stirring exploration of destiny, memory, and unspoken love.", "Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora's family emigrates from South Korea. Two decades later, they are reunited.", "1h 45m", "Paramount+", ["Greta Lee", "Teo Yoo", "John Magaro"], "kA244xewhis", ["paramount", "prime"]),
    ("The Batman", "Matt Reeves", 2022, 4.6, 4.5, ["Action", "Crime", "Noir"], "A gritty, noir-infused detective thriller that redefines Gotham.", "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.", "2h 56m", "HBO Max", ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"], "mqqft2x_Aa4", ["hbo", "prime"]),
    ("Top Gun: Maverick", "Joseph Kosinski", 2022, 4.8, 4.9, ["Action", "Aviation", "Blockbuster"], "Pure cinematic adrenaline with jaw-dropping practical aerial stunts.", "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOPGUN's elite graduates.", "2h 11m", "Paramount+", ["Tom Cruise", "Miles Teller", "Jennifer Connelly"], "giXco2jaZ_4", ["paramount", "prime"]),
    ("Avatar: The Way of Water", "James Cameron", 2022, 4.4, 4.5, ["Sci-Fi", "Adventure", "Visual FX"], "A spectacular underwater miracle that proves James Cameron remains unrivaled.", "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri.", "3h 12m", "Disney+", ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"], "d9MyW72ELq0", ["disney"]),
    ("Whiplash", "Damien Chazelle", 2014, 4.9, 4.8, ["Drama", "Music", "Intense"], "A relentless, electrifying clash between obsession and perfectionism.", "A promising young drummer enlists at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.", "1h 47m", "Hulu", ["Miles Teller", "J.K. Simmons", "Melissa Benoist"], "7d_jQycdQGo", ["hulu", "prime"]),
    ("Spirited Away", "Hayao Miyazaki", 2001, 4.9, 4.9, ["Animation", "Fantasy", "Classic"], "Hayao Miyazaki's spellbinding, timeless animation masterpiece.", "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.", "2h 5m", "HBO Max", ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"], "ByXuk9QqQkk", ["hbo"]),
    ("Pulp Fiction", "Quentin Tarantino", 1994, 4.9, 4.8, ["Crime", "Classic", "Cult"], "Tarantino's iconic non-linear crime classic that reshaped modern cinema.", "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", "2h 34m", "Paramount+", ["John Travolta", "Uma Thurman", "Samuel L. Jackson"], "s7EdQ4FqbhY", ["paramount", "prime"])
]

series_raw = [
    ("The Bear", "FX / Hulu", 2023, 4.9, 4.7, ["Drama", "Culinary", "Intense"], "Chaotic, heartfelt, and perfectly seasoned — the finest ensemble drama on TV.", "A young chef from the fine-dining world comes home to Chicago to run his family sandwich shop after a heartbreaking death.", "3 Seasons", "Hulu / Disney+", ["Jeremy Allen White", "Ayo Edebiri", "Ebon Moss-Bachrach"], "6w3N3jiS6Xo", ["hulu", "disney"]),
    ("Severance", "Apple TV+", 2022, 4.8, 4.6, ["Thriller", "Mystery", "Dystopian"], "A brilliantly unsettling workplace thriller that turns work-life balance inside out.", "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.", "2 Seasons", "Apple TV+", ["Adam Scott", "Britt Lower", "John Turturro"], "xEQP4VV0pjU", ["appleTv"]),
    ("Slow Horses", "Apple TV+", 2023, 4.6, 4.5, ["Spy", "Thriller", "Dark Comedy"], "A dry, riveting spy caper led by Gary Oldman at his most gloriously disheveled.", "Follows a team of British intelligence agents who serve in the dumping-ground department of MI5 called Slough House.", "4 Seasons", "Apple TV+", ["Gary Oldman", "Jack Lowden", "Kristin Scott Thomas"], "Ok3Z2Y2n1Lk", ["appleTv"]),
    ("Abbott Elementary", "ABC", 2024, 4.7, 4.6, ["Comedy", "Mockumentary", "Heartwarming"], "Warm, hilarious, and effortlessly charming — the best sitcom on TV.", "A group of dedicated teachers are brought together in a Philadelphia public school where they are determined to help their students succeed.", "4 Seasons", "Hulu / Max", ["Quinta Brunson", "Tyler James Williams", "Janelle James"], "pqE9oK3x_1A", ["hulu", "hbo"]),
    ("Succession", "HBO", 2023, 4.9, 4.8, ["Drama", "Corporate", "Satire"], "A razor-sharp Shakespearean tragedy about wealth, power, and toxic family dynamics.", "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down.", "4 Seasons", "HBO Max", ["Brian Cox", "Jeremy Strong", "Sarah Snook"], "OzYxJV_rmE8", ["hbo"]),
    ("Breaking Bad", "AMC", 2013, 4.9, 4.9, ["Crime", "Drama", "Masterpiece"], "The gold standard of television drama — flawless from beginning to end.", "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student.", "5 Seasons", "Netflix", ["Bryan Cranston", "Aaron Paul", "Anna Gunn"], "HhesaQXLuRY", ["netflix"]),
    ("The Last of Us", "HBO", 2023, 4.8, 4.7, ["Post-Apocalyptic", "Drama", "Horror"], "A breathtakingly emotional video game adaptation that sets a new high mark.", "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.", "1 Season", "HBO Max", ["Pedro Pascal", "Bella Ramsey"], "uLtkt8BonwM", ["hbo"]),
    ("House of the Dragon", "HBO", 2024, 4.6, 4.5, ["Fantasy", "Epic", "Drama"], "Fire, blood, and fierce political intrigue return to Westeros in grand fashion.", "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.", "2 Seasons", "HBO Max", ["Matt Smith", "Emma D'Arcy", "Olivia Cooke"], "DotnJ7tTA34", ["hbo"]),
    ("Shogun", "FX / Hulu", 2024, 4.9, 4.8, ["Historical", "Epic", "Drama"], "A magnificent, sweeping samurai saga steeped in honor, political cunning, and blood.", "When a mysterious European ship is found maroond in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power.", "1 Season", "Hulu / Disney+", ["Hiroyuki Sanada", "Cosmo Jarvis", "Anna Sawai"], "yAN5uspOALs", ["hulu", "disney"]),
    ("The Boys", "Amazon Prime", 2024, 4.7, 4.6, ["Superhero", "Satire", "Action"], "Viciously funny and unapologetically graphic commentary on corporate superheroes.", "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.", "4 Seasons", "Amazon Prime", ["Karl Urban", "Jack Quaid", "Antony Starr"], "06rueu_fh30", ["prime"]),
    ("Stranger Things", "Netflix", 2022, 4.7, 4.8, ["Sci-Fi", "80s Nostalgia", "Horror"], "Pure 80s nostalgia blended with supernatural thriller thrills.", "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.", "4 Seasons", "Netflix", ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"], "b9EkMc79ZSU", ["netflix"]),
    ("Ted Lasso", "Apple TV+", 2023, 4.7, 4.8, ["Comedy", "Heartwarming", "Sports"], "Unapologetically wholesome comedy that melts even the coldest hearts.", "An American football coach is hired to manage a British soccer team. What he lacks in knowledge, he makes up for with optimism.", "3 Seasons", "Apple TV+", ["Jason Sudeikis", "Hannah Waddingham", "Brett Goldstein"], "3u7EIiohtXc", ["appleTv"]),
    ("The White Lotus", "HBO", 2022, 4.6, 4.4, ["Dark Comedy", "Satire", "Mystery"], "A deliciously uncomfortable satire on wealth, privilege, and resort living.", "A sharp social satire following the exploits of various employees and guests at an exclusive Hawaiian resort over the span of one highly volatile week.", "2 Seasons", "HBO Max", ["Jennifer Coolidge", "Aubrey Plaza", "Sydney Sweeney"], "TGLq7_MonZ4", ["hbo"]),
    ("Euphoria", "HBO", 2022, 4.3, 4.2, ["Drama", "Teen", "Visual"], "A stylistically hyper-vibrant look at teenage anxiety, addiction, and love.", "A look at life for a group of high school students as they grapple with issues of drugs, sex, and violence.", "2 Seasons", "HBO Max", ["Zendaya", "Hunter Schafer", "Sydney Sweeney"], "c_nCqc71QNo", ["hbo"]),
    ("Fargo", "FX / Hulu", 2024, 4.7, 4.6, ["Crime", "Dark Comedy", "Anthology"], " Quirky, violent Midwestern crime tales crafted with cinematic flair.", "Various chronicles of deception, intrigue and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back one way or another to Fargo.", "5 Seasons", "Hulu", ["Juno Temple", "Jon Hamm", "Martin Freeman"], "g7j8p3w8B-M", ["hulu"]),
    ("Beef", "Netflix", 2023, 4.7, 4.5, ["Dark Comedy", "Drama", "Feud"], "A road rage encounter spirals into an all-consuming, hilarious rivalry.", "Two strangers get into a road rage incident that brings out their darkest impulses and consumes their lives.", "1 Season", "Netflix", ["Steven Yeun", "Ali Wong"], "AFPIMHBzGDs", ["netflix"]),
    ("Fleabag", "BBC / Amazon Prime", 2019, 4.9, 4.8, ["Comedy", "Drama", "Masterpiece"], "A dry, razor-sharp masterpiece about grief, love, and breaking the fourth wall.", "A dry-witted woman, known only as Fleabag, has no filter as she navigates life and love in London while trying to cope with tragedy.", "2 Seasons", "Amazon Prime", ["Phoebe Waller-Bridge", "Andrew Scott"], "aX2ViKQFL_k", ["prime"]),
    ("True Detective", "HBO", 2024, 4.6, 4.4, ["Crime", "Mystery", "Atmospheric"], "Dark, atmospheric murder mysteries anchored by powerhouse lead performances.", "Seasonal anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.", "4 Seasons", "HBO Max", ["Jodie Foster", "Matthew McConaughey", "Woody Harrelson"], "fVQUcaO4AvE", ["hbo"]),
    ("Game of Thrones", "HBO", 2019, 4.7, 4.7, ["Fantasy", "Epic", "Classic"], "The cultural phenomenon that set the bar for television worldbuilding.", "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.", "8 Seasons", "HBO Max", ["Emilia Clarke", "Kit Harington", "Peter Dinklage"], "gcTkNV5Vg1E", ["hbo"]),
    ("Black Mirror", "Netflix", 2023, 4.6, 4.6, ["Sci-Fi", "Dystopian", "Anthology"], "An unsettling anthology exploring the dark side of technology and human nature.", "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.", "6 Seasons", "Netflix", ["Daniel Kaluuya", "Bryce Dallas Howard", "Aaron Paul"], "V0XOApF5nLU", ["netflix"]),
    ("Arcane", "Netflix", 2021, 4.9, 4.9, ["Animation", "Sci-Fi", "Masterpiece"], "A visual marvel with stunning worldbuilding, complex characters, and emotional weight.", "Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions and the power that will tear them apart.", "1 Season", "Netflix", ["Hailee Steinfeld", "Ella Purnell"], "fXmAurh012s", ["netflix"]),
    ("Fallout", "Amazon Prime", 2024, 4.7, 4.7, ["Sci-Fi", "Post-Apocalyptic", "Action"], "A pitch-perfect adaptation blending retro-futuristic charm with wasteland violence.", "In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.", "1 Season", "Amazon Prime", ["Ella Purnell", "Walton Goggins", "Aaron Moten"], "V-mugKDQAlk", ["prime"]),
    ("Baby Reindeer", "Netflix", 2024, 4.6, 4.4, ["Drama", "Thriller", "Psychological"], "A raw, deeply uncomfortable autobiographical tale of stalking and trauma.", "When a struggling comedian shows a simple act of kindness to a vulnerable woman, it sparks a suffocating obsession that threatens to wreck both their lives.", "1 Season", "Netflix", ["Richard Gadd", "Jessica Gunning"], "eafmh5TjEow", ["netflix"]),
    ("Only Murders in the Building", "Hulu", 2024, 4.6, 4.6, ["Mystery", "Comedy", "Cosy"], "Delightful cozy mystery trio with incredible comedic chemistry.", "Three strangers who share an obsession with true crime podcasts suddenly find themselves wrapped up in one when a gruesome death occurs inside their exclusive Upper West Side apartment building.", "4 Seasons", "Hulu / Disney+", ["Steve Martin", "Martin Short", "Selena Gomez"], "-V1rQdXXXyI", ["hulu", "disney"]),
    ("The Crown", "Netflix", 2023, 4.7, 4.5, ["Historical", "Drama", "Royal"], "A lavish, impeccably acted chronicle of Queen Elizabeth II's reign.", "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.", "6 Seasons", "Netflix", ["Claire Foy", "Olivia Colman", "Imelda Staunton"], "JWtnJjn6ng0", ["netflix"])
]

songs_raw = [
    ("Espresso", "Sabrina Carpenter", 2024, 4.5, 4.7, ["Pop", "Summer Anthem", "Catchy"], "Bubbly, confident, and impossibly catchy — the defining track of summer 2024.", "A disco-tinged pop anthem about being unforgettable, with playful lyrics and infectious groove.", "2:55", "Spotify / Apple Music", ["Sabrina Carpenter"], "eVli-tstM5E", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Not Like Us", "Kendrick Lamar", 2024, 4.7, 4.9, ["Hip-Hop", "West Coast", "Diss Track"], "A thunderous, unapologetic West Coast anthem that dominated the culture.", "Produced by Mustard, 'Not Like Us' is a hard-hitting West Coast hip-hop track that became a global phenomenon.", "4:34", "Spotify / Apple Music", ["Kendrick Lamar"], "H63otTNQHzk", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Birds of a Feather", "Billie Eilish", 2024, 4.6, 4.8, ["Alt-Pop", "Dreamy", "Love Song"], "Wistful and intimate, Billie crafts a love song that feels both fragile and eternal.", "A shimmering alt-pop ballad about wanting to stay with someone forever, showcasing Eilish's delicate vocals.", "3:30", "Spotify / Apple Music", ["Billie Eilish"], "D461i153-fQ", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Die With A Smile", "Lady Gaga & Bruno Mars", 2024, 4.4, 4.6, ["Pop", "Soul", "Power Ballad"], "A soaring duet that pairs two of pop's biggest voices for a timeless ballad.", "Lady Gaga and Bruno Mars deliver a dramatic, retro-styled power ballad about wanting to spend your final moments together.", "4:11", "Spotify / Apple Music", ["Lady Gaga", "Bruno Mars"], "8atztHc0J8o", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Good Luck, Babe!", "Chappell Roan", 2024, 4.8, 4.9, ["Pop", "80s Pop", "Queer Anthem"], "An explosive, theatrical pop masterpiece with 80s synth hooks and incredible vocals.", "Chappell Roan Sings about compulsory heterosexuality and regret in an irresistible synth-pop belt.", "3:38", "Spotify / Apple Music", ["Chappell Roan"], "1-QG8D6_kCg", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Please Please Please", "Sabrina Carpenter", 2024, 4.6, 4.7, ["Pop", "Country-Pop", "Witty"], "Country-tinted pop gloss with sharp, witty lyrics about hoping your partner behaves.", "A retro country-pop track produced by Jack Antonoff with Carpenter's humorous plea to keep her reputation intact.", "3:06", "Spotify / Apple Music", ["Sabrina Carpenter"], "cF1Na4AIecM", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Cruel Summer", "Taylor Swift", 2023, 4.7, 4.8, ["Pop", "Synth-Pop", "Bridge Legend"], "A fan-favorite synth-pop anthem with one of the most satisfying bridges in modern music.", "A fever-dream pop track depicting the high-stakes emotional turbulence of a secret summer romance.", "2:58", "Spotify / Apple Music", ["Taylor Swift"], "ic8j13pcaZc", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Flowers", "Miley Cyrus", 2023, 4.5, 4.6, ["Pop", "Disco", "Self-Love"], "An empowering self-love disco anthem that broke streaming records worldwide.", "A disco-funk anthem celebrating independence and self-reliance following a high-profile breakup.", "3:20", "Spotify / Apple Music", ["Miley Cyrus"], "G7KNmW9a75Y", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Vampire", "Olivia Rodrigo", 2023, 4.6, 4.7, ["Pop-Rock", "Drama", "Piano Ballad"], "A dramatic piano ballad that swells into a thunderous pop-rock crescendo.", "Rodrigo channels raw betrayal and anger toward an older partner who exploited her fame and trust.", "3:39", "Spotify / Apple Music", ["Olivia Rodrigo"], "RlPNh_PB68Q", ["spotify", "appleMusic", "youtubeMusic"]),
    ("As It Was", "Harry Styles", 2022, 4.6, 4.7, ["Synth-Pop", "Indie", "Upbeat"], "A melancholic synth-pop bop masked under an upbeat, infectious 80s beat.", "Harry Styles reflects on personal change, isolation, and moving forward amidst life transformations.", "2:47", "Spotify / Apple Music", ["Harry Styles"], "H5v3kku4y6Q", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Blinding Lights", "The Weeknd", 2020, 4.9, 4.9, ["Synthwave", "80s", "Record-Breaker"], "The record-shattering 80s synthwave juggernaut that redefined modern pop.", "A retro 80s synthwave track detailing the longing for a partner while speeding down city streets at night.", "3:20", "Spotify / Apple Music", ["The Weeknd"], "4NRXx6U8ABQ", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Anti-Hero", "Taylor Swift", 2022, 4.5, 4.6, ["Pop", "Synth-Pop", "Vulnerable"], "Self-deprecating, deeply relatable pop confessing inner insecurities.", "Taylor Swift examines her own flaws, nightmare scenarios, and intrusive thoughts over a pulsing synth-pop rhythm.", "3:20", "Spotify / Apple Music", ["Taylor Swift"], "b1kbLwvqugk", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Kill Bill", "SZA", 2023, 4.7, 4.8, ["R&B", "Alt-R&B", "Dark Pop"], "A breezy R&B melody masking dark, humorous revenge fantasies.", "SZA explores toxic post-breakup envy and revenge fantasies inspired by the iconic Quentin Tarantino film.", "2:33", "Spotify / Apple Music", ["SZA"], "SQnc1QibElQ", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Seven", "Jung Kook ft. Latto", 2023, 4.4, 4.6, ["UK Garage", "Pop", "Catchy"], "A smooth UK garage pop jam celebrating loving someone seven days a week.", "Jung Kook delivers a smooth, effortless UK garage groove expressing romantic devotion all week long.", "3:04", "Spotify / Apple Music", ["Jung Kook", "Latto"], "QU9c0053UAU", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Stay", "The Kid LAROI & Justin Bieber", 2021, 4.5, 4.6, ["Pop-Punk", "Synth-Pop", "Upbeat"], "An upbeat synth-pop collaboration packed with frantic emotional energy.", "A high-energy pop track about pleading with a partner to stay despite one's own self-destructive habits.", "2:21", "Spotify / Apple Music", ["The Kid LAROI", "Justin Bieber"], "kTJczUoc56U", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Levitating", "Dua Lipa", 2020, 4.8, 4.8, ["Disco-Pop", "Dance", "Upbeat"], "Pure disco-pop euphoria designed to keep dance floors moving.", "A shimmering disco-pop hit filled with funky basslines, cosmic metaphors, and irresistible dance energy.", "3:23", "Spotify / Apple Music", ["Dua Lipa"], "TUVcZfQe-Kw", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Starboy", "The Weeknd ft. Daft Punk", 2016, 4.8, 4.8, ["R&B", "Electropop", "Classic"], "Dark electropop luxury produced by legendary duo Daft Punk.", "The Weeknd reflects on his metamorphosis into an international superstar over Daft Punk's dark synth bass line.", "3:50", "Spotify / Apple Music", ["The Weeknd", "Daft Punk"], "34Na4j8AVgA", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Paint The Town Red", "Doja Cat", 2023, 4.5, 4.6, ["Hip-Hop", "Jazz-Rap", "Sassy"], "A bold jazz-sampled rap track asserting unapologetic self-confidence.", "Sampling Dionne Warwick's 'Walk On By', Doja Cat delivers a cool, unbothered rap anthem ignoring online critics.", "3:51", "Spotify / Apple Music", ["Doja Cat"], "m4_9TFeMfCI", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Fast Car", "Luke Combs", 2023, 4.6, 4.7, ["Country", "Cover", "Storytelling"], "A respectful, soaring country rendition of Tracy Chapman's timeless storytelling classic.", "Combs pays homage to Tracy Chapman's iconic 1988 song about escaping economic hardship and dreaming of a better life.", "4:25", "Spotify / Apple Music", ["Luke Combs"], "Tr6f8bFmU6k", ["spotify", "appleMusic", "youtubeMusic"]),
    ("I Can Do It With a Broken Heart", "Taylor Swift", 2024, 4.5, 4.6, ["Synth-Pop", "Dance-Pop", "Emotional"], "High-energy electropop masking the heartbreak of performing live while hurting inside.", "Swift sings about powering through stadium tours and putting on a smile despite dealing with severe personal grief.", "3:38", "Spotify / Apple Music", ["Taylor Swift"], "Sl_j862v96U", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Houdini", "Dua Lipa", 2023, 4.5, 4.5, ["Dance-Pop", "Psychedelic", "Club"], "A psychedelic club bop with hypnotic basslines and Dua's signature cool confidence.", "A hypnotic dance-pop track about vanishing like the famous magician if a partner doesn't keep up.", "3:05", "Spotify / Apple Music", ["Dua Lipa"], "suAR1PYFNYA", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Water", "Tyla", 2023, 4.6, 4.7, ["Amapiano", "Afrobeats", "Sultry"], "Sultry Amapiano rhythms that brought South African dance sound to global airwaves.", "Tyla fuses South African Amapiano with R&B for a smooth, sultry summer dance anthem.", "3:20", "Spotify / Apple Music", ["Tyla"], "XoiOOiuH8iI", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Greedy", "Tate McRae", 2023, 4.5, 4.6, ["Pop", "Dance-Pop", "Enthusiastic"], "A punchy, fast-paced pop track driven by fierce vocal confidence.", "Tate McRae delivers a high-octane pop anthem about knowing your worth and turning heads.", "2:11", "Spotify / Apple Music", ["Tate McRae"], "Trp0c_p4wI0", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Lose Control", "Teddy Swims", 2024, 4.7, 4.8, ["Soul", "R&B", "Power Vocal"], "A raw, thunderous soul ballad showcasing one of the most powerful voices in music.", "Teddy Swims pours his heart out about toxic codependency over a retro R&B/soul instrumental.", "3:30", "Spotify / Apple Music", ["Teddy Swims"], "GZ3zL7Ap66w", ["spotify", "appleMusic", "youtubeMusic"]),
    ("Texas Hold 'Em", "Beyoncé", 2024, 4.6, 4.7, ["Country", "Americana", "Dance"], "A joyous, banjo-plucked country hoedown that topped global charts.", "Beyoncé embraces country music with Rhiannon Giddens on banjo, inviting everyone to lay their cards down and dance.", "3:55", "Spotify / Apple Music", ["Beyoncé"], "238N04bXA8U", ["spotify", "appleMusic", "youtubeMusic"])
]

podcasts_raw = [
    ("Huberman Lab", "Dr. Andrew Huberman", 2024, 4.6, 4.8, ["Science", "Health", "Deep Dive"], "Science-backed breakdowns of sleep, focus, and performance — dense but rewarding.", "Dr. Andrew Huberman discusses neuroscience and science-based tools for everyday health, focus, and physical performance.", "~2h episodes", "Spotify / Apple Podcasts", ["Andrew Huberman"], "MN8qTzq8VhY", ["spotify", "appleTv", "youtube"]),
    ("Crime Junkie", "Audiochuck", 2024, 4.3, 4.5, ["True Crime", "Weekly", "Investigative"], "Addictive true-crime storytelling with a conversational tone that keeps listeners hooked.", "Ashley Flowers and Brit Prawat bring you a weekly podcast covering fascinating true crime cases from missing persons to solved murders.", "~1h episodes", "Spotify / Apple Podcasts", ["Ashley Flowers", "Brit Prawat"], "3KZhTqFqQgY", ["spotify", "appleTv", "youtube"]),
    ("How I Built This", "NPR", 2024, 4.5, 4.7, ["Business", "Startup", "Interviews"], "Founders share the raw, human stories behind the brands that changed our lives.", "Guy Raz interviews the world's best-known entrepreneurs to learn how they built iconic global companies from scratch.", "~45m episodes", "Spotify / Apple Podcasts", ["Guy Raz"], "D7e3qJvNqYU", ["spotify", "appleTv", "youtube"]),
    ("The Daily", "The New York Times", 2024, 4.6, 4.5, ["News", "Daily", "Journalism"], "Essential daily listening for anyone who wants to understand the world.", "The biggest stories of our time, reported by journalists from The New York Times. Hosted by Michael Barbaro and Sabrina Tavernise.", "~20m episodes", "Spotify / Apple Podcasts", ["Michael Barbaro", "Sabrina Tavernise"], "8hJ2Yd5p8hU", ["spotify", "appleTv", "youtube"]),
    ("The Joe Rogan Experience", "Joe Rogan", 2024, 4.5, 4.6, ["Interviews", "Comedy", "Longform"], "Longform, unfiltered conversations with scientists, comedians, athletes, and thinkers.", "Joe Rogan hosts longform, wide-ranging conversations with guests spanning science, martial arts, philosophy, comedy, and technology.", "~3h episodes", "Spotify", ["Joe Rogan"], "p_T-S88jK3w", ["spotify", "youtube"]),
    ("Anything Goes with Emma Chamberlain", "Emma Chamberlain", 2024, 4.4, 4.6, ["Lifestyle", "Personal", "Solo"], "Intimate, rambling thoughts on life, fashion, mental health, and growing up.", "Emma Chamberlain records from her bed or closet, offering candid thoughts on philosophy, relationships, anxiety, and pop culture.", "~45m episodes", "Spotify / Apple Podcasts", ["Emma Chamberlain"], "v7N-0G3FjE8", ["spotify", "appleTv"]),
    ("SmartLess", "Wondery", 2024, 4.7, 4.7, ["Comedy", "Celebrity", "Interviews"], "Hilarious, improvised banter as three famous friends interview surprise guests.", "Jason Bateman, Sean Hayes, and Will Arnett connect people from all walks of life. One host reveals a surprise guest to the other two.", "~1h episodes", "Spotify / Apple Podcasts", ["Jason Bateman", "Sean Hayes", "Will Arnett"], "tGzGg7K646E", ["spotify", "appleTv"]),
    ("Call Her Daddy", "Alex Cooper", 2024, 4.5, 4.6, ["Relationships", "Celebrity", "Lifestyle"], "Unfiltered discussions on sex, relationships, mental health, and celebrity culture.", "Alex Cooper dives into relationships, sex, advice, and high-profile celebrity interviews with total honesty.", "~1h episodes", "Spotify", ["Alex Cooper"], "8qH9vN5cZ0E", ["spotify", "appleTv"]),
    ("Stuff You Should Know", "iHeartPodcasts", 2024, 4.6, 4.7, ["Education", "Trivia", "Curiosity"], "Charming breakdowns of how everything in the world works, from chaos theory to cast iron.", "Josh Clark and Chuck Bryant educate listeners on everything from champagne to true crime to science.", "~45m episodes", "Spotify / Apple Podcasts", ["Josh Clark", "Chuck Bryant"], "f71_k02K5Qk", ["spotify", "appleTv"]),
    ("On Purpose with Jay Shetty", "Jay Shetty", 2024, 4.6, 4.7, ["Self-Help", "Mindfulness", "Wellness"], "Wisdom on love, purpose, and mental health from a former monk turned global author.", "Jay Shetty shares fascinating conversations with insightful guests on wisdom, purpose, relationships, and mindfulness.", "~1h episodes", "Spotify / Apple Podcasts", ["Jay Shetty"], "L6N4a5b-kM8", ["spotify", "youtube"]),
    ("Radiolab", "WNYC Studios", 2024, 4.8, 4.8, ["Science", "Storytelling", "Audio Design"], "Immersive, sound-rich soundscapes investigating deep scientific and philosophical questions.", "Radiolab is a show about curiosity, where science collides with culture and information is woven into soundscapes.", "~1h episodes", "Spotify / Apple Podcasts", ["Jad Abumrad", "Latif Nasser"], "y7L9sN9j8a0", ["spotify", "appleTv"]),
    ("Serial", "The New York Times", 2024, 4.9, 4.8, ["True Crime", "Journalism", "Investigative"], "The groundbreaking podcast that launched the modern true crime genre.", "Sarah Koenig unravels one true story over the course of a season, exposing flaws in the justice system.", "~45m episodes", "Spotify / Apple Podcasts", ["Sarah Koenig"], "a0A5V9Vb3E0", ["spotify", "appleTv"]),
    ("Lex Fridman Podcast", "Lex Fridman", 2024, 4.6, 4.7, ["AI", "Technology", "Deep Dive"], "In-depth conversations about AI, robotics, physics, history, and human consciousness.", "Lex Fridman speaks with scientists, researchers, programmers, and world leaders about artificial intelligence and the future.", "~3h episodes", "Spotify / YouTube", ["Lex Fridman"], "p-j7qS8t4a0", ["spotify", "youtube"]),
    ("Armchair Expert with Dax Shepard", "Dax Shepard", 2024, 4.5, 4.6, ["Interviews", "Psychology", "Comedy"], "Candid interviews exploring the messiness of being human.", "Dax Shepard and Monica Padman explore the messiness of being human with celebrities, academics, and experts.", "~2h episodes", "Spotify / Apple Podcasts", ["Dax Shepard", "Monica Padman"], "k5M9v3N8b2Q", ["spotify", "appleTv"]),
    ("The Diary Of A CEO", "Steven Bartlett", 2024, 4.7, 4.8, ["Business", "Self-Improvement", "Success"], "Intimate, unscripted wisdom from world-class entrepreneurs and experts.", "Steven Bartlett sits down with influential leaders to learn the unscripted truth behind success, health, and mindsets.", "~1h 30m episodes", "Spotify / Apple Podcasts", ["Steven Bartlett"], "p9M2b7N4x0Q", ["spotify", "youtube"]),
    ("Heavyweight", "Gimlet / Spotify", 2024, 4.9, 4.9, ["Storytelling", "Empathy", "Humor"], "Jonathan Goldstein helps ordinary people return to a moment in their past to resolve regrets.", "Jonathan Goldstein helps people go back to a moment in their life when everything went wrong to seek closure.", "~45m episodes", "Spotify / Apple Podcasts", ["Jonathan Goldstein"], "x7N2v5K8m0P", ["spotify", "appleTv"]),
    ("CONAN O'BRIEN NEEDS A FRIEND", "Team Coco", 2024, 4.8, 4.8, ["Comedy", "Interviews", "Hilarious"], "Conan O'Brien searches for real friendships with famous celebrities.", "After 25 years as a late-night host, Conan realizes he's never made real friends with his guests, so he invites them to hang out.", "~1h episodes", "Spotify / Apple Podcasts", ["Conan O'Brien", "Sona Movsesian"], "c9P2b4M6v0Q", ["spotify", "appleTv"]),
    ("Modern Wisdom", "Chris Williamson", 2024, 4.7, 4.8, ["Self-Improvement", "Psychology", "Life Hacks"], "Lessons in human nature, fitness, productivity, and mindset from world experts.", "Chris Williamson interviews top minds in psychology, biology, fitness, and philosophy to help you understand life.", "~1h 30m episodes", "Spotify / Apple Podcasts", ["Chris Williamson"], "m8N3v2K9b1P", ["spotify", "youtube"]),
    ("Dan Carlin's Hardcore History", "Dan Carlin", 2024, 4.9, 4.9, ["History", "Masterpiece", "Epic"], "Monumental 4-hour historical audio sagas told with unmatched intensity.", "Dan Carlin brings history to life in epic, deeply researched 4-hour audio chronicles of humanity's greatest wars.", "~4h episodes", "Spotify / Apple Podcasts", ["Dan Carlin"], "h7M2b9P4v0K", ["spotify", "appleTv"]),
    ("Mind Pump: Raw Fitness Truth", "Mind Pump Media", 2024, 4.6, 4.7, ["Fitness", "Health", "Nutrition"], "Busting fitness myths with honest, science-backed workout and nutrition advice.", "Sal Di Stefano, Adam Schafer, and Justin Andrews shed light on the fitness industry with raw, honest training advice.", "~1h 15m episodes", "Spotify / Apple Podcasts", ["Sal Di Stefano", "Adam Schafer"], "n9P2v4K8b0Q", ["spotify", "youtube"]),
    ("Darknet Diaries", "Jack Rhysider", 2024, 4.8, 4.8, ["Cybersecurity", "True Crime", "Hacking"], "Thrilling true stories from the dark side of the internet — hackers, heists, and cyberwarfare.", "Jack Rhysider explores true stories of hackers, cybercrime, surveillance, and government covert operations.", "~50m episodes", "Spotify / Apple Podcasts", ["Jack Rhysider"], "d8M3b2V9p1K", ["spotify", "appleTv"]),
    ("Planet Money", "NPR", 2024, 4.6, 4.7, ["Economics", "Fun", "Education"], "The global economy explained through fun, creative, and human stories.", "Imagine you could call a friend and say 'Meet me at the bar and tell me what's happening with the economy.' That's Planet Money.", "~25m episodes", "Spotify / Apple Podcasts", ["Robert Smith", "Amanda Aronczyk"], "p7N2v9K4b0Q", ["spotify", "appleTv"]),
    ("Rotten Mango", "Stephanie Soo", 2024, 4.7, 4.8, ["True Crime", "Deep Dive", "Storytelling"], "Detailed true crime storytelling focused on international cases and psychological analysis.", "Stephanie Soo dives deep into dark, lesser-known international true crime cases with vivid detail and empathy.", "~1h 30m episodes", "Spotify / Apple Podcasts", ["Stephanie Soo"], "r9M2b4K8v0P", ["spotify", "youtube"]),
    ("Modern Love", "The New York Times", 2024, 4.5, 4.6, ["Romance", "Personal", "Essays"], "Heartfelt stories of love, loss, and redemption read by famous actors.", "Famous essays on love, loss, betrayal, and redemption from The New York Times column, read by notable personalities.", "~30m episodes", "Spotify / Apple Podcasts", ["Anna Martin"], "m7N2v4P8b0K", ["spotify", "appleTv"]),
    ("Freakonomics Radio", "Stephen J. Dubner", 2024, 4.6, 4.7, ["Economics", "Behavior", "Curiosity"], "Discover the hidden side of everything with co-author of the best-selling books.", "Stephen Dubner explores the riddles of everyday life and uncovers the hidden economic forces driving human behavior.", "~45m episodes", "Spotify / Apple Podcasts", ["Stephen J. Dubner"], "f8M3b9P2v0Q", ["spotify", "appleTv"])
]

def build_data():
    items = []
    item_id = 1
    
    for category, raw_list in [('Movies', movies_raw), ('Series', series_raw), ('Songs', songs_raw), ('Podcasts', podcasts_raw)]:
        for title, creator, year, rating, aud_rating, tags, excerpt, desc, duration, platform, cast, trailer_id, offers in raw_list:
            art = None
            if category == 'Series':
                art = None
                try:
                    q = title.replace(' ', '+')
                    url = f'https://api.tvmaze.com/singlesearch/shows?q={q}'
                    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                    res = urllib.request.urlopen(req, timeout=4)
                    data = json.loads(res.read().decode('utf-8'))
                    art = data.get('image', {}).get('original', '')
                except Exception:
                    pass
            
            if not art and category in ['Movies', 'Series']:
                try:
                    q = f'{title} Soundtrack' if category == 'Movies' else title
                    url = f'https://itunes.apple.com/search?term={q.replace(" ", "+")}&limit=3'
                    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                    res = urllib.request.urlopen(req, timeout=4)
                    data = json.loads(res.read().decode('utf-8'))
                    if data.get('results'):
                        art = data['results'][0].get('artworkUrl100', '').replace('100x100bb', '600x600bb')
                except Exception:
                    pass
            
            if not art and category == 'Songs':
                try:
                    q = f'{title} {creator}'
                    url = f'https://itunes.apple.com/search?term={q.replace(" ", "+")}&media=music&limit=3'
                    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                    res = urllib.request.urlopen(req, timeout=4)
                    data = json.loads(res.read().decode('utf-8'))
                    if data.get('results'):
                        art = data['results'][0].get('artworkUrl100', '').replace('100x100bb', '600x600bb')
                except Exception:
                    pass
            
            if not art and category == 'Podcasts':
                try:
                    q = title
                    url = f'https://itunes.apple.com/search?term={q.replace(" ", "+")}&media=podcast&limit=3'
                    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                    res = urllib.request.urlopen(req, timeout=4)
                    data = json.loads(res.read().decode('utf-8'))
                    if data.get('results'):
                        art = data['results'][0].get('artworkUrl100', '').replace('100x100bb', '600x600bb')
                except Exception:
                    pass
            
            if not art:
                # Fallback to high quality category unsplash image
                fallbacks = {
                    'Movies': 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1000&auto=format&fit=crop',
                    'Series': 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?q=80&w=1000&auto=format&fit=crop',
                    'Songs': 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1000&auto=format&fit=crop',
                    'Podcasts': 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=1000&auto=format&fit=crop'
                }
                art = fallbacks[category]

            colors = {
                'Movies': 'from-orange-400 to-amber-600',
                'Series': 'from-blue-500 to-indigo-700',
                'Songs': 'from-pink-400 to-rose-600',
                'Podcasts': 'from-emerald-400 to-teal-700'
            }

            item = {
                'id': item_id,
                'title': title,
                'category': category,
                'creator': creator,
                'year': year,
                'rating': rating,
                'audienceRating': aud_rating,
                'coverColor': colors[category],
                'tags': tags,
                'excerpt': excerpt,
                'description': desc,
                'duration': duration,
                'platform': platform,
                'cast': cast,
                'trailerUrl': f'https://www.youtube.com/embed/{trailer_id}',
                'streamingOffers': offers,
                'imageUrl': art
            }
            items.append(item)
            print(f'Item {item_id}: [{category}] {title} -> {art[:60]}...')
            item_id += 1
            time.sleep(0.1)

    print(f'Total items generated: {len(items)}')
    return items

if __name__ == '__main__':
    items = build_data()
    with open('100_reviews.json', 'w', encoding='utf-8') as f:
        json.dump(items, f, indent=2)
    print('Saved 100_reviews.json successfully!')
